version: "3.9"

services:
  go-gin-api:
    build: .
    container_name: go-gin-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres  
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres
    depends_on:
      - postgres
    networks:
      - mynetwork
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

volumes:
  pgdata:

networks:
  mynetwork:
